### ISSUE TITLE
개발 모드와 배포 모드 비밀번호 오류 문제

### ISSUE THREAD

**Issue by jel-lambda** [saintdragon2/do_it_django_a_to_z#3]
안녕하세요, 감사히도 좋은 책을 만나 도커로 개발하던 중 문제가 생겼습니다.
찾아봐도 좋은 해결책을 찾지 못하여 이렇게 남깁니다.

배포용을 개발하다, 개발용으로 개발하고 싶을 때,
`docker-compose down -v`
명령어로 볼륨을 다 지워버리면 배포 버전 데이터베이스에 저장한 데이터가 모두 날아가버리는 것 같은데, 배포 모드 데이터를 유지하면서 개발 모드를 이용할 방법은 없을까요?
만약 down -v를 하지 않고 그냥 down 하면,
postgresql 암호인증이 되지 않습니다.(아이디와 비밀번호는 책과 같이 개발용과 배포용을 분리하여 서로 다르게 설정해두었습니다.)
migrate을 할 때, 

`django.db.utils.OperationalError: FATAL: password authentication failed for user "user_prod"
`

이러한 오류가 뜨고 docker-compose up 을 해둔 창에서는 아래와 같이 뜹니다.

```
db_1  |  2021-01-19 15:28:47.139 UTC [46] FATAL: password authentication failed for  user "user_prod"
db_1  |  2021-01-19 15:28:47.139 UTC [46] DETAIL: Role "user_prod" does not exist.
```

위와 같은 오류가 발생하게 되는데, 해결 방법이 있을까요?

**Comment by godseun** [comment]
안녕하세요, 저도 이 책으로 도커를 만나 관심을 가지게 되어 공부중인 독자입니다.
만약 저라면 2가지 방법 중 한가지를 선택해서 써볼거같아요!
1. `docker-compose exec db /bin/bash` 계정과 패스워드를 생성한다. ( ! 책을 그대로 따라하셨다면 서비스이름이 db 이겟죠)
2. docker-compose.yml 파일안에 들어갈 .env... 파일에서 계정, 비밀번호를 변경한다.

이렇게하시면 해결될거같습니다.

**Comment by taegon** [comment]
@sheee7 님, 저희 책을 선택해 주셔서 감사합니다.
독자이신 @godseun 님께서 공유해주신 것처럼, 이미 만들어진 데이터베이스 볼륨이 있으면, 접속하여 계정을 추가하실 수도 있습니다. 아니면 두 환경의 설정을 동일하게 설정하여 계정정보를 동일하게 사용하실 수도 있습니다. 아마 두번째 방법이 더 수월한 방법일 것입니다.

저희가 개발버전과 배포버전을 분리하여 설명한 것은 웹서비스 개발시 운영되는 서비스를 중지하지 않고, 지속적으로 개발하기 위해서는 기본적으로 필요한 구조임을 보여드리기 위해서입니다. 그래서 저희는 개발과정에는 임시 데이터를 자유롭게 저장하고, 지우고, 가짜 계정을 만들어보는 등의 작업을 가정하고, 운영시에는 빈 데이터베이스 (깨끗한 상태)에서 서비스를 운용할 것으로 생각하고, 책의 코드를 구성하였습니다.

질문 주신 것처럼 개발과정에서 입력한 정보를 그대로 서비스에 사용하고 싶은 경우에는 개발환경에서 사용한 아이디와 비밀번호를 그대로 이용하여 사용하실 수 있습니다. 다른 방식으로는 데이터를 백업하여 텍스트파일을 추출한 후, 서비스할 데이터베이스에 복구하는 방식을 이용하실 수도 있습니다. 또 다른 방식으로는 시스템 초기화시 입력되어야 할 기본 정보를 코드로 남겨둘 수도 있습니다. 테스트 코드에서 작업한 것처럼, 예를 들어 공지글이나, 기본적으로 제공되어야 할 계정들은 코드에 직접 남겨둘 수도 있습니다. 이렇게 하면 볼륨을 지우고 데이터베이스를 새로 만들더라도, 장고 서비스가 처음 구동될 때, 필요한 데이터를 정해진 코드에 따라 입력해 둘 수 있습니다.

혹시 문제가 해결이 안되시면 언제든 다시 알려주세요.

**Comment by jel-lambda** [comment]
답변 감사드립니다. 덕분에 잘 해결했습니다!
