### ISSUE TITLE
letsencrypt 인증서 발급 변경 이슈

### ISSUE THREAD

**Issue by ljh95** [saintdragon2/do_it_django_a_to_z#4]
안녕하세요 책을 보며 따라가고 있는 학생입니다.

다름이 아니라 책 마지막부분 ssl인증 부분에서 letsencrypt 인증서 발급 방식이 조금 변경된 것 같은데 
제가 실수를 한건지 아니면 변경되서 막히는게 맞는지 궁금해서 올립니다.

현재 책 기준으로 
init-letsencrypy.sh 를 생성할 경우 404 not found만 나와서 그렇습니다.

그래서 혼자 해결해 보려고 하는 https://happist.com/573990/%EC%B5%9C%EC%8B%A0-lets-encrypt-ssl-%EC%9D%B8%EC%A6%9D%EC%84%9C-%EB%B0%9C%EA%B8%89-%EB%B0%A9%EB%B2%95-3%EA%B0%80%EC%A7%80-%EC%A0%95%EB%A6%AC 
이 사이트에서 
![image](https://user-images.githubusercontent.com/40597662/106998682-3d083400-67c8-11eb-999f-dd15a6cdb27e.png)
어떤 방식을 사용하는게 가장 이상적인지 
제가 docker를 이용해 light sails에 배포해보는건 처음이라 판별이 어렵네요 
긴글 읽어주셔서 감사합니다.!

**Comment by taegon** [comment]
@ljh95 님 책을 선택해주셔서 감사합니다. 벌써 마지막 부분까지 학습을 하셨나 보네요. 언제든 의견 남겨주세요.

일단 빠르게 답변을 드리자면, 책에 제공된 url 경로가 다르게 되었네요. 불편을 드려서 죄송합니다.
아래 명령으로 실행하시면, 정상적으로 스크립트 파일을 받으실 수 있을 겁니다.
`curl -L https://raw.githubusercontent.com/wmnnd/nginx-certbot/master/init-letsencrypt.sh > init-letsencrypt.sh`
책에서는 `curl -L https://raw.githubusercontent.com/wmnnd/nginx-certbot/main/init-letsencrypt.sh > init-letsencrypt.sh`로 서술되어 있는데, 브랜치명(main -> master)이 다르게 되어 있습니다.

HTTPS인증 관련해서는 인터넷에서 자료들을 쉽게 찾아볼 수 있고, 다양한 방법들이 존재합니다. 하지만 각각 설정방식이 조금씩 다르기 때문에, 저희 책을 따라할 것을 추천드립니다. 저희가 가장 쉬운 방법이라고 생각되는 방식을 골라서 책에 담았고, 해당 스크립트도 저희 저장소가 아닌 원저작자의 링크를 이용하고 있는 것도 최신버전에 더욱 잘 대응할 수 있는 방법이라고 생각했기 때문입니다. 책을 따라하시다가 발생한 문제는 현재 설정된 환경을 저희가 알기 때문에 도와드리기가 훨씬 수월합니다.

혹시 이후에 문제가 있으시면 언제든 질문 남겨주세요. 그리고 저희가 책의 코드를 그대로 이용하여 운영하고 있는 웹사이트에 질문게시판을 만들어 두었으니, 그곳을 이용해주시면, 다른 독자분들과 함께 고민을 나누실 수 있을 것 같습니다. 고맙습니다.
https://doitdjango.com/board/qna/

**Comment by taegon** [comment]
그리고 참고하신 블로그를 살펴보았는데, 정확히 1,2,3,4로 구분되는 건 아닌 것 같습니다. 해당 글을 쓰신 분이 주관적으로 방법을 설명하기 위해 나눈 방법인데, 저희가 소개한 방식은 2번 방식에 가깝다고 보입니다. letsencrypt 인증서는 인증서를 발급받고, 발급 후 90일 안에 재갱신을 해주어야 하는데, 이는 1번 방식과 유사한 형태로 진행이 됩니다.

**Comment by ljh95** [comment]
감사합니다 덕분에 인증서는 제대로 다운받아졌습니다!
